### ISSUE TITLE
Error while running amp-viewer-client npm copybuild 

### ISSUE THREAD

**Issue by guybartal** [Azure/live-video-analytics#108]
`npm run copybuild`

![image](https://user-images.githubusercontent.com/3179107/93725247-316bf600-fbb6-11ea-95c4-93b1e006702b.png)

2020-09-20T23_56_51_430Z-debug.log:

```

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\gubert\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'copybuild'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.16.1
4 verbose run-script [ 'precopybuild', 'copybuild', 'postcopybuild' ]
5 info lifecycle amp-client@1.0.15~precopybuild: amp-client@1.0.15
6 info lifecycle amp-client@1.0.15~copybuild: amp-client@1.0.15
7 verbose lifecycle amp-client@1.0.15~copybuild: unsafe-perm in lifecycle true
8 verbose lifecycle amp-client@1.0.15~copybuild: PATH: C:\Users\gubert\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\gubert\Repos\live-video-analytics\utilities\amp-viewer\amp-viewer-client\node_modules\.bin;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\PuTTY\;C:\Program Files\dotnet\;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files (x86)\Graphviz2.38\bin;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\LINQPad5;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PowerShell\7\;C:\Users\gubert\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\gubert\AppData\Local\Yarn\bin;C:\Program Files (x86)\Graphviz2.38\bin;C:\Users\gubert\.dotnet\tools;C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy;C:\Tools\draft-v0.16.0-windows-amd64\windows-amd64\;C:\Tools\terraform;C:\Users\gubert\AppData\Local\Programs\Fiddler;C:\Tools\WinDiff;C:\Program Files\Microsoft SDKs\Azure\Azure Dev Spaces CLI (Preview);C:\Users\gubert\AppData\Local\Microsoft\WindowsApps;C:\Python27;C:\Users\gubert\AppData\Roaming\npm;C:\Users\gubert\.dotnet\tools
9 verbose lifecycle amp-client@1.0.15~copybuild: CWD: C:\Users\gubert\Repos\live-video-analytics\utilities\amp-viewer\amp-viewer-client
10 silly lifecycle amp-client@1.0.15~copybuild: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   './node_modules/cpr/bin/cpr client_dist ../amp-viewer/client_dist -d'
10 silly lifecycle ]
11 silly lifecycle amp-client@1.0.15~copybuild: Returned: code: 1  signal: null
12 info lifecycle amp-client@1.0.15~copybuild: Failed to exec copybuild script
13 verbose stack Error: amp-client@1.0.15 copybuild: `./node_modules/cpr/bin/cpr client_dist ../amp-viewer/client_dist -d`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\gubert\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\gubert\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid amp-client@1.0.15
15 verbose cwd C:\Users\gubert\Repos\live-video-analytics\utilities\amp-viewer\amp-viewer-client
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gubert\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "copybuild"
18 verbose node v12.16.1
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error amp-client@1.0.15 copybuild: `./node_modules/cpr/bin/cpr client_dist ../amp-viewer/client_dist -d`
22 error Exit status 1
23 error Failed at the amp-client@1.0.15 copybuild script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by anilmur** [comment]
Ack, asking @sseiber to take a look. Thanks

**Comment by sseiber** [comment]
@guybartal - this step (the copybuild script in the package.json file) is supposed to copy the typescript build output (in client_dist) to a peer folder named "amp-viewer". See line 10 (the third one) in the output above. Make sure you have cloned this peer project "amp-viewer" before building the the "amp-viewer-client".

Also, I'm assuming you are interested in making customizations since this viewer has a pre-built container at:
mcr.microsoft.com/lva-utilities/amp-viewer:1.0-amd64

Let me know how it goes.

**Comment by sseiber** [comment]
@guybartal - just remembered this is all one project (live-video-analytics) so you should have the peer directories when you cloned. Please verify.

**Comment by guybartal** [comment]
@sseiber, both projects indeed located in the same repo, I've just followed the instructions on this [readme.md] (https://github.com/Azure/live-video-analytics/tree/master/utilities/amp-viewer) and got this error late at night so I didn't dig in.

Something is wrong with the execution of cpr module inside npm while running from windows, probably the differences in the path format between Linux and Windows, because when I run it on WSL2 with ubuntu 18.04 it works.

If I run it manually from windows cmd line like this, it copies the file files to amp_viewer:

> C:\Users\gubert\Repos\live-video-analytics\utilities\amp-viewer\amp-viewer-client>node "node_modules\cpr\bin\cpr" client_dist ..\amp-viewer\client_dist -d
> 
> C:\Users\gubert\Repos\live-video-analytics\utilities\amp-viewer\amp-viewer-client>dir ..\amp-viewer\client_dist
>  Volume in drive C is OSDisk
>  Volume Serial Number is FC57-5D1D
> 
>  Directory of C:\Users\gubert\Repos\live-video-analytics\utilities\amp-viewer\amp-viewer\client_dist
> 
> 10/01/2020  12:21 AM    <DIR>          .
> 10/01/2020  12:21 AM    <DIR>          ..
> 10/01/2020  12:21 AM    <DIR>          assets
> 10/01/2020  12:21 AM             1,085 index.html
> 10/01/2020  12:21 AM            47,747 index.js
> 10/01/2020  12:21 AM            66,618 index.js.map
> 10/01/2020  12:21 AM           974,864 vendor.js
> 10/01/2020  12:21 AM         3,941,678 vendor.js.map
>                5 File(s)      5,031,992 bytes
>                3 Dir(s)  111,702,130,688 bytes free

anyway, I also figured it out that there's a pre-built container, so in case I'll need to customize now I know what to do.

Thanks Scott.

**Comment by gadamilan** [comment]
@guybartal  @sseiber 
Do we consider this issue closed now?

**Comment by sseiber** [comment]
@gadamilan I will update the sample with a library that works on Windows.

**Comment by anilmur** [comment]
The sample has been updated (https://github.com/Azure/live-video-analytics/pull/119).

**Comment by guybartal** [comment]
Thanks!
