### ISSUE TITLE
Module Initialization Failure

### ISSUE THREAD

**Issue by waitingkuo** [Azure/live-video-analytics#126]
Got this error while intialization. What's the potential reason that cause this? Is there any workaround to fix this? Thanks.

```
<3> 2020-10-23 17:16:21.752 +00:00 Application: Module initialization failure
Unhandled exception. System.InvalidOperationException: Client version 2020-07-07 is not supported.
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClient.GetSupportedVersion(String serverSupportedApiVersion, String clientSupportedApiVersion)
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClient.GetVersionedWorkloadClient(Uri workloadUri, String serverSupportedApiVersion, String clientSupportedApiVersion, String moduleId, String moduleGenerationId)
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClient..ctor(Uri serverUri, String serverSupportedApiVersion, String clientSupportedApiVersion, String moduleId, String moduleGenerationId)
   at Microsoft.Azure.Devices.Edge.Util.Edged.EncryptionProvider..ctor(Uri workloadUri, String workloadApiVersion, String apiClientVersion, String moduleId, String moduleGenerationid, String initializationVector)
   at Microsoft.Azure.Devices.Edge.Util.Edged.EncryptionProvider.CreateAsync(String storagePath, Uri workloadUri, String edgeletApiVersion, String edgeletClientApiVersion, String moduleId, String genId, String initializationVectorFileName)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Common.Encryption.EncryptionParametersStore.InitializeAsync()
   at Microsoft.Media.LiveVideoAnalytics.Edge.Common.Encryption.EncryptionParametersStore.CreateAsync(IIotEncryptionConfiguration encryptionConfiguration, IFileOperations fileOperations, String storagePath)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Common.Encryption.EdgeEncryptionProviderFactory.CreateAsync(IFileOperations fileOperations, IIotEncryptionConfiguration encryptionConfiguration, String storagePath)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Components.UsageManager.DataStore.UsageManagerDataStore.CreateAsync(IUsageManagerConfiguration usageManagerConfiguration, IFileOperations fileOperations, IEdgeEncryptionProviderFactory encryptionProviderFactory)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Components.UsageManager.UsageManager.InitializeAsync()
   at Microsoft.Media.LiveVideoAnalytics.Edge.Components.UsageManager.UsageManager.CreateAsync(IEdgeModuleContext iotEdgeModuleContext, IUsageManagerConfiguration usageManagerConfiguration, IEdgeAmsClientAccessor amsClientAccessor, IEdgeGraphManager graphManager, IEdgeModuleManager edgeModuleManager, IFileOperations fileOperations, IStopwatch stopwatch, IEdgeEncryptionProviderFactory encryptionProviderFactory, IPolicyProvider policyProvider, IUsagePolicyEvaluator usagePolicyEvaluator)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Components.UsageManager.UsageManagerFactory.CreateAsync(IEdgeModuleContext iotEdgeModuleContext, IFileOperations fileOperations, IUsageManagerConfiguration usageManagerConfiguration, IEdgeAmsClientAccessor edgeAmsClientAccessor, IEdgeGraphManager graphManager, IEdgeModuleManager edgeModuleManager, IStopwatch stopwatch, IEdgeEncryptionProviderFactory encryptionProviderFactory)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Core.MediaEdgeModule.InitializeAsync()
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Core.MediaEdgeModule.InitializeAsync()
   at Microsoft.Media.LiveVideoAnalytics.Edge.Common.Hosts.IoTEdge.EdgeHost.SetModuleAsync(IEdgeModule module)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Program.Main(String[] args)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Program.Main(String[] args)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Program.<Main>(String[] args)
!! production readiness: user accounts – Warning
       LOCAL_USER_ID and LOCAL_GROUP_ID environment variables are not set. The program will run as root!
       For optimum security, make sure to set LOCAL_USER_ID and LOCAL_GROUP_ID environment variables to a non-root user and group.
       See https://aka.ms/lva-iot-edge-prod-checklists-user-accounts for more information.
<6> 2020-10-23 17:21:24.906 +00:00 Application: Module telemetry is enabled. System usage data that helps Microsoft improve this product will be reported.
<6> 2020-10-23 17:21:25.081 +00:00 Events: {
  "id": "45c2fa87-eb29-4d2b-b405-6720d32874c5",
  "topic": "/subscriptions/9d89029e-3e7f-473c-be93-27aee0774923/resourcegroups/demovideoanalytics/providers/microsoft.media/mediaservices/ams001",
  "subject": "",
  "eventType": "Microsoft.Media.Graph.Diagnostics.RuntimeError",
  "eventTime": "2020-10-23T17:21:25.041Z",
  "data": {
    "code": "ModuleInitializationFailure"
  },
  "dataVersion": "1.0"
}
<6> 2020-10-23 17:22:01.286 +00:00 Application: Request started: Method name: 'GraphInstanceList'.; Context: activityId=8ce5e2bc-fc42-4208-bafd-862493c47aa2
<3> 2020-10-23 17:22:25.324 +00:00 Application: Module initialization failure
Unhandled exception. System.InvalidOperationException: Client version 2020-07-07 is not supported.
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClient.GetSupportedVersion(String serverSupportedApiVersion, String clientSupportedApiVersion)
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClient.GetVersionedWorkloadClient(Uri workloadUri, String serverSupportedApiVersion, String clientSupportedApiVersion, String moduleId, String moduleGenerationId)
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClient..ctor(Uri serverUri, String serverSupportedApiVersion, String clientSupportedApiVersion, String moduleId, String moduleGenerationId)
   at Microsoft.Azure.Devices.Edge.Util.Edged.EncryptionProvider..ctor(Uri workloadUri, String workloadApiVersion, String apiClientVersion, String moduleId, String moduleGenerationid, String initializationVector)
   at Microsoft.Azure.Devices.Edge.Util.Edged.EncryptionProvider.CreateAsync(String storagePath, Uri workloadUri, String edgeletApiVersion, String edgeletClientApiVersion, String moduleId, String genId, String initializationVectorFileName)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Common.Encryption.EncryptionParametersStore.InitializeAsync()
   at Microsoft.Media.LiveVideoAnalytics.Edge.Common.Encryption.EncryptionParametersStore.CreateAsync(IIotEncryptionConfiguration encryptionConfiguration, IFileOperations fileOperations, String storagePath)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Common.Encryption.EdgeEncryptionProviderFactory.CreateAsync(IFileOperations fileOperations, IIotEncryptionConfiguration encryptionConfiguration, String storagePath)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Components.UsageManager.DataStore.UsageManagerDataStore.CreateAsync(IUsageManagerConfiguration usageManagerConfiguration, IFileOperations fileOperations, IEdgeEncryptionProviderFactory encryptionProviderFactory)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Components.UsageManager.UsageManager.InitializeAsync()
   at Microsoft.Media.LiveVideoAnalytics.Edge.Components.UsageManager.UsageManager.CreateAsync(IEdgeModuleContext iotEdgeModuleContext, IUsageManagerConfiguration usageManagerConfiguration, IEdgeAmsClientAccessor amsClientAccessor, IEdgeGraphManager graphManager, IEdgeModuleManager edgeModuleManager, IFileOperations fileOperations, IStopwatch stopwatch, IEdgeEncryptionProviderFactory encryptionProviderFactory, IPolicyProvider policyProvider, IUsagePolicyEvaluator usagePolicyEvaluator)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Components.UsageManager.UsageManagerFactory.CreateAsync(IEdgeModuleContext iotEdgeModuleContext, IFileOperations fileOperations, IUsageManagerConfiguration usageManagerConfiguration, IEdgeAmsClientAccessor edgeAmsClientAccessor, IEdgeGraphManager graphManager, IEdgeModuleManager edgeModuleManager, IStopwatch stopwatch, IEdgeEncryptionProviderFactory encryptionProviderFactory)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Core.MediaEdgeModule.InitializeAsync()
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Core.MediaEdgeModule.InitializeAsync()
   at Microsoft.Media.LiveVideoAnalytics.Edge.Common.Hosts.IoTEdge.EdgeHost.SetModuleAsync(IEdgeModule module)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Program.Main(String[] args)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Program.Main(String[] args)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Program.<Main>(String[] args)
!! production readiness: user accounts – Warning
       LOCAL_USER_ID and LOCAL_GROUP_ID environment variables are not set. The program will run as root!
       For optimum security, make sure to set LOCAL_USER_ID and LOCAL_GROUP_ID environment variables to a non-root user and group.
       See https://aka.ms/lva-iot-edge-prod-checklists-user-accounts for more information.
<6> 2020-10-23 17:27:28.654 +00:00 Application: Module telemetry is enabled. System usage data that helps Microsoft improve this product will be reported.
<6> 2020-10-23 17:27:28.835 +00:00 Events: {
  "id": "5f62d163-d9a5-4670-80c4-cb12ad286924",
  "topic": "/subscriptions/9d89029e-3e7f-473c-be93-27aee0774923/resourcegroups/demovideoanalytics/providers/microsoft.media/mediaservices/ams001",
  "subject": "",
  "eventType": "Microsoft.Media.Graph.Diagnostics.RuntimeError",
  "eventTime": "2020-10-23T17:27:28.791Z",
  "data": {
    "code": "ModuleInitializationFailure"
  },
  "dataVersion": "1.0"
}
```

**Comment by naiteeks** [comment]
Hi @waitingkuo,

Can you share some steps that you did to encounter this issue? 

Also, from your edge device, please collect logs and share with us. The command to collect logs will be:
sudo iotedge support-bundle --since 2h

Note: Please reproduce the issue and then collect the logs so that it will help in diagnosing the issue.

**Comment by naiteeks** [comment]
Hello @waitingkuo ,

The above issue is because of an issue with the Iotedge module. Can you please update that module to v1.0.10 and test? Here is the [link](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge) that will help in updating the module.

**Comment by gadamilan** [comment]
Closing due to lack of response
