### ISSUE TITLE
deepstream lvaExtension showing error message Value: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_7328043147756932471'

### ISSUE THREAD

**Issue by Devinwong** [Azure/live-video-analytics#193]
Hi I am trying the deepstream lva extension sample code.
The modules are running from docker ps.
```
CONTAINER ID        IMAGE                                                    COMMAND                   CREATED             STATUS              PORTS                                                                  NAMES
51789ee50898        devinworacroqaigatl.azurecr.io/lva-gst-deepstream:0309   "/bin/sh -c 'exec /a…"    2 hours ago         Up 2 hours          0.0.0.0:5001->5001/tcp, 0.0.0.0:8080->80/tcp                           lvaExtension
752a2c3bca11        mcr.microsoft.com/azureiotedge-hub:1.0                   "/bin/sh -c 'echo \"$…"   2 days ago          Up 24 hours         0.0.0.0:443->443/tcp, 0.0.0.0:5671->5671/tcp, 0.0.0.0:8883->8883/tcp   edgeHub
81def297c1cd        mcr.microsoft.com/media/live-video-analytics:2           "/usr/local/bin/entr…"    2 days ago          Up 24 hours         9600/tcp                                                               lvaEdge
0bf195a2c34c        mcr.microsoft.com/azureiotedge-agent:1.0                 "/bin/sh -c 'exec /a…"    2 days ago          Up 25 hours                                                                                edgeAgent
```

The lva extension logs kept report the following error.

```
[2021-03-19 09:20:39,963] [ThreadPoolEx] [INFO]: Exception:
        File name: /app/shared_memory.py
        Line number: 49
        Line: self._shmFile.close()
        Value: 'SharedMemoryManager' object has no attribute '_shmFile'
[2021-03-19 09:20:40,067] [ThreadPoolEx] [INFO]: Exception:
        File name: /app/shared_memory.py
        Line number: 20
        Line: self._shmFile = open(self._shmFileFullPath, 'r+b')
        Value: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_7328043147756932471'
[2021-03-19 09:20:40,067] [ThreadPoolEx] [INFO]: Exception:
        File name: /app/inference_server.py
        Line number: 52
        Line: size=self._mediaStreamDescriptor.shared_memory_buffer_transfer_properties.length_bytes)
        Value: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_7328043147756932471'
[2021-03-19 09:20:40,067] [ThreadPoolEx] [ERROR]: Exception iterating responses: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_7328043147756932471'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/grpc/_server.py", line 453, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "/app/inference_server.py", line 164, in ProcessMediaStream
    clientState = State(mediaStreamMessageRequest.media_stream_descriptor)
  File "/app/inference_server.py", line 52, in __init__
    size=self._mediaStreamDescriptor.shared_memory_buffer_transfer_properties.length_bytes)
  File "/app/shared_memory.py", line 20, in __init__
    self._shmFile = open(self._shmFileFullPath, 'r+b')
FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_7328043147756932471'
```

And in the /dev/shm, it doesn't have the share_memory file or folder.
root@51789ee50898:/dev/shm# ls
lttng-ust-wait-8

Seems the share memory wasn't enabled properly?

Attached the deployment manifest and operations.json with Container Registry credentials removed.
[deployment.zip](https://github.com/Azure/live-video-analytics/files/6170082/deployment.zip)

ps. I am using an IP camera so RTSP sim module is not running.
nvidia-smi works well on the host machine.

**Comment by anilmur** [comment]
Ack, checking...

**Comment by nicolasbotto** [comment]
Hi @Devinwong , the lvaEdge module in your manifest deployment file is missing the IpcMode which is required for using gRPC with shared memory. Please take a look at the manifest file located in the deployment folder (utilities/video-analysis/deepstream/deployment). 
https://github.com/Azure/live-video-analytics/blob/14f2e0293f51e2488c0ffb1bea8729d958507481/utilities/video-analysis/deepstream/deployment/deployment.deepstream.template.json#L72

**Comment by naiteeks** [comment]
@Devinwong  - are you unblocked with the above response?

**Comment by gadamilan** [comment]
@Devinwong - Closing this as I believe this was resolved
