### ISSUE TITLE
lvaEdge module initialisation error

### ISSUE THREAD

**Issue by Sherinmath** [Azure/live-video-analytics#74]
I am getting this error when I run lvaEdge 1.0 or 1.0.2 on ubuntu...Please help

<3> 2020-07-18 05:38:23.678 +00:00 Application: Module initialization failure
Unhandled exception. Microsoft.Media.LiveVideoAnalytics.Edge.Common.Core.Exceptions.EdgeException: The path /var/lib/azuremediaservices/AmsApplicationData specified for ApplicationDataDirectory desired property is being used for another module. Please make sure the path being specified is not being used by any other module.
 ---> Microsoft.Media.LiveVideoAnalytics.Edge.Common.Core.Exceptions.FileOperationException: UnauthorizedAccess
   at Microsoft.Media.LiveVideoAnalytics.Edge.Common.Core.FileOperations.TryGetFileException(Exception ex, String filePath, FileOperationException& fileEx)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Common.Core.FileOperations.AcquireFileLock(String filePath, FileShare fileShareType)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.DataIntegrityEnforcer.AcquireModuleDataLock()
   --- End of inner exception stack trace ---
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.DataIntegrityEnforcer.AcquireModuleDataLock()
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.DataIntegrityEnforcer.EnsureApplicationDirectoryDataIsValidAsync()
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.MediaEdgeModule.InitializeAsync()
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.MediaEdgeModule.InitializeAsync()
   at Microsoft.Media.LiveVideoAnalytics.Edge.Common.Hosts.IoTEdge.EdgeHost.SetModuleAsync(IEdgeModule module)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Program.Main(String[] args)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Program.Main(String[] args)
   at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Program.<Main>(String[] args)

**Comment by Sherinmath** [comment]
Sorry that was an issue with bind mounting the folder...hence closing the issue

**Comment by Sherinmath** [comment]
Sorry that was an issue with bind mounting the folder...hence closing the issue

**Comment by gadamilan** [comment]
Hi @Sherinmath 
Wanted to check with you and see if you got everything working fine or if you needed any more help?
